# Generated by Django 5.2 on 2025-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='apiKey',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
