# Generated by Django 5.2 on 2025-05-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_partner_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='activationStatus',
            field=models.CharField(choices=[('pending', 'en attente'), ('in progress', 'en cours'), ('success', 'terminé'), ('failed', 'échoué')], default='pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
