# Generated by Django 5.2 on 2025-05-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_profileattribute_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in progress', 'En cours'), ('finished', 'Terminé'), ('failed', 'Echoué')], default='pending')),
                ('score', models.IntegerField()),
                ('details', models.CharField()),
                ('version', models.CharField()),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
