# Generated by Django 5.2 on 2025-05-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='details',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='version',
            field=models.CharField(blank=True, null=True),
        ),
    ]
