# Generated by Django 5.2 on 2025-05-06 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_analyse_details_alter_analyse_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='regex',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('string', 'Texte'), ('integer', 'Entier'), ('float', 'Décimal'), ('date', 'Date'), ('boolean', 'Booléen'), ('choice', 'Choix'), ('json', 'JSON'), ('file', 'Fichier')]),
        ),
        migrations.CreateModel(
            name='ProfileAttributeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField()),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('txt', 'txt')])),
                ('downloadedAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending')),
                ('metadata', models.CharField(blank=True, null=True)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
