# Generated by Django 5.2 on 2025-05-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profileattributedocument_titre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileattributedocument',
            name='titre',
            field=models.CharField(choices=[('bank_statement', 'Relevé bancaire'), ('proof_of_address', 'Justificatif de domicile')]),
        ),
    ]
