# Generated by Django 5.2 on 2025-05-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_profileattributedocument_titre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileattributedocument',
            old_name='titre',
            new_name='title',
        ),
    ]
