# Generated by Django 5.2 on 2025-05-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_titre_profileattributedocument_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analyse',
            new_name='Analysis',
        ),
    ]
