# Generated by Django 5.2 on 2025-05-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_analyse_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='completedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
