# Generated by Django 5.2 on 2025-05-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_webhook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='profile',
        ),
        migrations.AddField(
            model_name='webhook',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.partner'),
        ),
    ]
