# Generated by Django 5.2 on 2025-05-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_webhook_profile_webhook_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('complete', 'Complet'), ('in analysis', 'En analyse'), ('analyzed', 'Analysé')], default='draft'),
        ),
    ]
