# Generated by Django 5.2 on 2025-05-13 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileattribute',
            name='attribute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.attribute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileattribute',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
            preserve_default=False,
        ),
    ]
