# Generated by Django 5.2 on 2025-05-13 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_profileattribute_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileattribute',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute'),
        ),
        migrations.AlterField(
            model_name='profileattribute',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profile'),
        ),
    ]
