# Generated by Django 5.2 on 2025-05-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_profileattribute_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileattributedocument',
            name='title',
        ),
    ]
