# Generated by Django 5.2 on 2025-05-15 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_profileattributedocument_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='isRequiredFor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.attribute'),
        ),
        migrations.AlterField(
            model_name='profileattributedocument',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('txt', 'TXT'), ('ODT', 'TXT')]),
        ),
    ]
