# Generated by Django 5.2 on 2025-05-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_attribute_isrequiredfor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='acceptedFormat',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='isEqualTo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='maxDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='maxLength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='maxSize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='maxValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='minDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='minLength',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='minValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='validation',
            field=models.CharField(blank=True, choices=[('regex', 'Expression régulière'), ('unique choice', 'Choix unique'), ('multiple choice', 'Choix multiple'), ('min/max value', 'Valeur minmale et maximale'), ('min/max length', 'Longueur minmale et maximale'), ('is equal to', 'Est égal à'), ('min/max date', 'Date minimale et maximale'), ('max size', 'Taille maximale')], null=True),
        ),
    ]
