# Generated by Django 5.2 on 2025-05-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_attribute_acceptedformat_attribute_isequalto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='isRequired',
            field=models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('conditionnally obligated', 'Conditionnellement obligatoire')], default='no'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='validation',
            field=models.CharField(blank=True, choices=[('regex', 'Expression régulière'), ('unique choice', 'Choix unique'), ('multiple choice', 'Choix multiple'), ('min/max value', 'Valeur minmale et maximale'), ('min/max length', 'Longueur minmale et maximale'), ('min/max date', 'Date minimale et maximale')], null=True),
        ),
    ]
