# Generated by Django 5.2 on 2025-05-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_attribute_isrequired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='isRequired',
            field=models.CharField(choices=[('yes', 'Oui'), ('no', 'Non'), ('conditionnally obligated', 'Conditionnellement obligatoire')]),
        ),
    ]
