# Generated by Django 5.2 on 2025-05-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_attribute_isrequired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='isRequiredFor',
        ),
        migrations.RemoveField(
            model_name='attributechoice',
            name='attribute',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='isRequired',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='AttributeAttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires', models.BooleanField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attribute')),
                ('attribute_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attributechoice')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='choices',
            field=models.ManyToManyField(through='api.AttributeAttributeChoice', to='api.attributechoice'),
        ),
    ]
