# Generated by Django 5.2 on 2025-05-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_attribute_isrequiredfor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributeattributechoice',
            old_name='requires',
            new_name='is_choice',
        ),
    ]
