# Generated by Django 5.2 on 2025-05-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_requires_attributeattributechoice_is_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributeattributechoice',
            old_name='is_choice',
            new_name='isChoice',
        ),
    ]
