# Generated by Django 5.2 on 2025-05-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_is_choice_attributeattributechoice_ischoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='maxDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='minDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
