# Generated by Django 5.2 on 2025-05-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_attribute_maxdate_alter_attribute_mindate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='attributeattributechoice',
            name='isChoice',
        ),
        migrations.AddField(
            model_name='attributechoice',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute'),
        ),
        migrations.AlterField(
            model_name='attributeattributechoice',
            name='attribute',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute'),
        ),
        migrations.AlterField(
            model_name='attributeattributechoice',
            name='attribute_choice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributechoice'),
        ),
        migrations.AlterField(
            model_name='attributechoice',
            name='displayedName',
            field=models.CharField(),
        ),
    ]
