# Generated by Django 5.2 on 2025-05-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_attribute_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='category',
            field=models.CharField(choices=[('personal data', 'Données personnelles'), ('identity document', "Pièce d'identité"), ('address', 'Adresse'), ('housing situation', "Situation d'habitation"), ('family situation', 'Situation familiale'), ('children', 'Enfants'), ('professional situation', 'Situation professionnelle'), ('product usage', 'Usage du produit'), ('income and expenses', 'Revenus et charge'), ('diverse', 'Divers'), ('documents', 'Documents')]),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='maxLength',
            field=models.IntegerField(blank=True, default=9223372036854775807, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='maxValue',
            field=models.FloatField(blank=True, default=9223372036854775807, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='minLength',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='minValue',
            field=models.FloatField(blank=True, default=-9223372036854775808, null=True),
        ),
    ]
