# Generated by Django 5.2 on 2025-05-16 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_attribute_category_alter_attribute_maxlength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeattributechoice',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attribute'),
        ),
        migrations.AlterField(
            model_name='attributeattributechoice',
            name='attribute_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributechoice'),
        ),
    ]
