# Generated by Django 5.2 on 2025-05-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_attributeattributechoice_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeattributechoice',
            name='attribute_choice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.attributechoice'),
        ),
    ]
