# Generated by Django 5.2 on 2025-05-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_attributeattributechoice_attribute_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
