# Generated by Django 5.2 on 2025-05-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_webhook_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhook',
            old_name='key',
            new_name='token',
        ),
    ]
