# Generated by Django 5.2 on 2025-05-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_key_webhook_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='maxLength',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
