# Generated by Django 5.2 on 2025-05-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_attribute_maxlength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='webhookUrl',
        ),
    ]
