# Generated by Django 5.2 on 2025-05-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_partner_webhookurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='apiKey',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
