# Generated by Django 5.2 on 2025-05-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_partner_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileattributedocument',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
