# Generated by Django 5.2 on 2025-05-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_profileattributedocument_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='isEqualTo',
        ),
        migrations.AlterField(
            model_name='profileattributedocument',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('txt', 'TXT'), ('odt', 'ODT')]),
        ),
    ]
